version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Install dependencies with Yarn
          command: yarn install
      - save_cache: # special step to save the dependency cache
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies with Yarn
          command: yarn install
      - run:
          name: Run lint
          command: yarn lint
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
workflows:
  version: 2
  Build and Lint:
    jobs:
      - build
      - lint
